title: "Yash Sharma "
email: yash37158@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Hey ! Im yash sharma from India currently doing my undergraduate in CS from Amity university Mumbai. My major skill
 set include Front End Web development , Android development and Beginner in open source contribution 
baseurl: "/" 
url: "yash37158.github.io/" 
twitter_username: yash37158
github_username:  yash37158

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
